server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Eureka ??? ??? Eureka ??? ???? ??? ??
    fetch-registry: false # Eureka ??? ?? Eureka ??? ???? ??? ???? ??? ??
  server:
    # Eureka ??? ???? ??? ???? ??? ??
    wait-time-in-ms-when-sync-empty: 0